var mymsg = "Hello Kashif, I have Started Learning Typscript" ;
console.log(mymsg);
var A = 1 ;
var B = 2 ;
var C = 3 ;
var D = 4 ;
var E = 5 ;
var F = 6 ;
var G = 7 ;
var H = 9 ;
var I = 10 ;
var J = 11 ;
var add = (A+B+C+D+E+F+G+H+I+J) ;
var sub = (J-I-H-G-F-E-D-C-B-A) ;
var mul = (A*B*C*D*E*F*G*H*I*J) ;
var div = (I/B) ;
console.log("Addition of Numbers",add) ;
console.log("Subtraction of Numbers",sub) ;
console.log("Multiplication of Numbers",mul) ;
console.log("Division of any Two Numbers",div) ;